language: python
python:
  - "2.6"
  - "2.7"

install: 
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt

script: python setup.py test

notifications:
  hipchat:
    - secure: "HqBUrmf4P2bgvwb4b9PL1tBae2wcZaXadOgwRwAFhdhDZFHaKXIXlJRUW8tN\ntdO83OZgatxJrpWWQj8VYTfDuhlE3b3NxVWeXc3PkfrHmuvejQf4veh7kwR0\njLVE6jb+ZbFIwRE2W0VFLFKYQHI6PLem4W0OKXW5Shqzy8Ewlow="
